export const AUTH_USER = 'AUTH_USER'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR'

export const GET_DATA_FROMLS = 'GET_DATA_FROMLS'
export const GET_DATA_FROMLS_SUCCESS = 'GET_DATA_FROMLS_SUCCESS'
export const GET_DATA_FROMLS_ERROR = 'GET_DATA_FROMLS_ERROR'

export const LOG_OUT = 'LOG_OUT'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR'