export const GET_NEWS = 'GET_NEWS'
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS'
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR'

export const ADD_NEWS = 'ADD_NEWS'
export const ADD_NEWS_SUCCESS = 'ADD_NEWS_SUCCESS'
export const ADD_NEWS_ERROR = 'ADD_NEWS_ERROR'

export const SELECT_NEWS_UPDATE = 'SELECT_NEWS_UPDATE'
export const START_UPDATE_NEWS = 'START_UPDATE_NEWS'
export const UPDATE_NEWS_SUCCESS = 'UPDATE_NEWS_SUCCESS'
export const UPDATE_NEWS_ERROR = 'UPDATE_NEWS_ERROR'

export const DELETE_NEWS = 'DELETE_NEWS'
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS'
export const DELETE_NEWS_ERROR = 'DELETE_NEWS_ERROR'