export const GET_PROBLEM = "GET_PROBLEM"
export const GET_PROBLEM_SUCCESS = "GET_PROBLEM_SUCCESS"
export const GET_PROBLEM_ERROR = "GET_PROBLEM_ERROR"

export const GET_PROBLEMS = 'GET_PROBLEMS'
export const GET_PROBLEMS_SUCCESS = 'GET_PROBLEMS_SUCCESS'
export const GET_PROBLEMS_ERROR = 'GET_PROBLEMS_ERROR'

export const ADD_PROBLEM = 'ADD_PROBLEM'
export const ADD_PROBLEM_SUCCESS = 'ADD_PROBLEM_SUCCESS'
export const ADD_PROBLEM_ERROR = 'ADD_PROBLEM_ERROR'

export const UPDATE_PROBLEM = 'UPDATE_PROBLEM'
export const UPDATE_PROBLEM_SUCCESS = 'UPDATE_PROBLEM_SUCCESS'
export const UPDATE_PROBLEM_ERROR = 'UPDATE_PROBLEM_ERROR'

export const DELETE_PROBLEM = 'DELETE_PROBLEM'
export const DELETE_PROBLEM_SUCCESS = 'DELETE_PROBLEM_SUCCESS'
export const DELETE_PROBLEM_ERROR = 'DELETE_PROBLEM_ERROR'