export const GET_SOLUTIONS = 'GET_SOLUTIONS'
export const GET_SOLUTIONS_SUCCESS = 'GET_SOLUTIONS_SUCCESS'
export const GET_SOLUTIONS_ERROR = 'GET_SOLUTIONS_ERROR'

export const GET_SOLUTION_BY_PROBLEM_ID = 'GET_SOLUTION_BY_PROBLEM_ID'
export const GET_SOLUTION_BY_PROBLEM_ID_SUCCESS = 'GET_SOLUTION_BY_PROBLEM_ID_SUCCESS'
export const GET_SOLUTION_BY_PROBLEM_ID_ERROR = 'GET_SOLUTION_BY_PROBLEM_ID_ERROR'

export const ADD_SOLUTION = 'ADD_SOLUTION'
export const ADD_SOLUTION_SUCCESS = 'ADD_SOLUTION_SUCCESS'
export const ADD_SOLUTION_ERROR = 'ADD_SOLUTION_ERROR'

export const UPDATE_SOLUTION = "UPDATE_SOLUTION"
export const UPDATE_SOLUTION_SUCCESS = "UPDATE_SOLUTION_SUCCESS"
export const UPDATE_SOLUTION_ERROR = "UPDATE_SOLUTION_ERROR"

export const DELETE_SOLUTION = 'DELETE_SOLUTION'
export const DELETE_SOLUTION_SUCCESS = 'DELETE_SOLUTION_SUCCESS'
export const DELETE_SOLUTION_ERROR = 'DELETE_SOLUTION_ERROR'